### ISSUE TITLE
get crowdastro working onserver

### ISSUE THREAD

**Issue by jbanfield** [chengsoonong/crowdastro#116]
@jbanfield needs to set up the RSAA server

**Comment by jbanfield** [comment]
following setup instructions.

`Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_julie/dask`

Error most likely the result of everything already installed?

**Comment by jbanfield** [comment]
looks like mongoDB is installed on the system but I can't seem to access it.

**Comment by MatthewJA** [comment]
Try:

`mongod --fork --logpath mongologs/log.txt --dbpath mongodata/`

From the /priv/myrtle1/julie/ directory. Starting mongod without specifying the dbpath explicitly doesn't seem to work &mdash; I believe that the default dbpath leads to a directory that doesn't exist.

**Comment by jbanfield** [comment]
seemed to work, but new error

`about to fork child process, waiting until server is ready for connections.
forked process: 7869
ERROR: child process failed, exited with error number 48
`

**Comment by MatthewJA** [comment]
```
2016-07-21T10:06:35.506+1000 E NETWORK  [initandlisten]   addr already in use
2016-07-21T10:06:35.506+1000 E STORAGE  [initandlisten] Failed to set up sockets during startup.
```

Looks like it's already running!

**Comment by jbanfield** [comment]
weird.  How to I end that and restart as I can't seem to locate that instance anywhere?

**Comment by MatthewJA** [comment]
It's running as PID `32029`, so I guess I started it the other day. I'll kill it and you can launch your own.

**Comment by MatthewJA** [comment]
Done.

**Comment by jbanfield** [comment]
Just finished uploading the required data to the directory.  Can you add this one? norris_2006_atlas_classifications_ra_dec_only.dat

**Comment by jbanfield** [comment]
I still get the same error

`about to fork child process, waiting until server is ready for connections.
forked process: 8379
ERROR: child process failed, exited with error number 100`

**Comment by MatthewJA** [comment]
Norris: Done. I'll also add documentation on where to get this file.
Error: It couldn't make the lock file (probably my fault still) &mdash; deleted the existing lock, try now?

**Comment by jbanfield** [comment]
nope

**Comment by jbanfield** [comment]
I'm logged into misfit.  What computer are you running on?

**Comment by jbanfield** [comment]
worked.  I opened another terminal window and then rerun the command.  Not sure if I need two open though

`about to fork child process, waiting until server is ready for connections.
forked process: 8892
child process started successfully, parent exiting`

**Comment by MatthewJA** [comment]
misfit also. I _think_ I've fixed it now (`mongod` didn't have permission to modify the data files since I ran it from my account, so I just deleted those) &mdash; it should work now.

**Comment by MatthewJA** [comment]
Yup, it's filled the mongodata directory with files that you can modify. Hopefully that should not be a problem in future.

If you included `--fork`, then you shouldn't need to keep the window open.

**Comment by jbanfield** [comment]
excellent.  I don't have the 03-01 sanatized data.  I only have 04-15.  Am I correct to assume that everything should still run with this new database?

**Comment by MatthewJA** [comment]
Yep, should be fine provided that the format hasn't changed.

**Comment by jbanfield** [comment]
Had to modify the following to change the path to RGZ

setup_data.sh
mongo_load_json.sh
crowdastro.json

**Comment by jbanfield** [comment]
Have successfully run the setup.

**Comment by MatthewJA** [comment]
Great! I've updated `setup.md` based on this to clarify what to do if the data is in a different place to where it's expected.

If the setup worked, then the instructions in the readme should work now.

**Comment by jbanfield** [comment]
running /usr/local/python-2.7.1/bin/python

doesn't like `python -m crowdastro.import_data`

`Traceback (most recent call last):`
 `File "/usr/local/python-2.7.1/lib/python2.7/runpy.py", line 162, in _run_module_as_main`
 `"__main__", fname, loader, pkg_name)`
`File "/usr/local/python-2.7.1/lib/python2.7/runpy.py", line 72, in _run_code`
 `exec code in run_globals`
`File "/priv/myrtle1/julie/crowdastro/crowdastro/import_data.py", line 22, in <module>`
 `from . import rgz_data as data`
`File "crowdastro/rgz_data.py", line 224`
`SyntaxError: Non-ASCII character '\xce' in file crowdastro/rgz_data.py on line 225, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details`

**Comment by MatthewJA** [comment]
I don't have Python 2, so I'm probably not going to be able to reliably troubleshoot this, but if you run `git pull origin master` you should receive a fix for the Python 2 syntax error above.

**Comment by MatthewJA** [comment]
Oh wait, I have server access... Looks like `pymongo` isn't installed. I'm not sure we have permissions to install it. Can we get that installed?

We need all of the libraries listed in `requirements.txt`.

**Comment by jbanfield** [comment]
I'll look into it.

**Comment by MatthewJA** [comment]
Just checked all the other dependencies and they seem to be installed. `pymongo` is the only one missing I think.

**Comment by jbanfield** [comment]
Is there anything I need to do to exit the mongod cleanly?  Also, if I get the same error as before when I go to run it, how do I locate the instance to exit/unlock it?

**Comment by MatthewJA** [comment]
Not sure, but I think you can run `mongod stop`. If you get the same error, the lock is in `mongodata`. The log files are in `mongologs` with the most recent being called `log.txt` &mdash; they usually make the problem clearer.

**Comment by MatthewJA** [comment]
Any updates on pymongo?

**Comment by jbanfield** [comment]
can't seem to run mongod again

`mongod --fork --logpath mongologs/log.txt --dbpath mongodata/`

still get the same error.  Looked at logs.txt and it says that it is already in use but I can't find it.

**Comment by MatthewJA** [comment]
Will take a look and see if I can get mongo running.

**Comment by MatthewJA** [comment]
> bind() failed errno:98 Address already in use for socket: 0.0.0.0:27017

This one means that MongoDB is already running. Checking running processes:

> julie     8892     1  1 Jul21 ?        02:18:38 mongod --fork --logpath mongologs/log.txt --dbpath mongodata/

I assume you're julie, so it should be good to go!

**Comment by jbanfield** [comment]
Weird I guess I didn't log out properly before

**Comment by MatthewJA** [comment]
I think it keeps running when you log out.

**Comment by jbanfield** [comment]
got the mongod command to work.

Get the same error as before when I run the `python -m crowdastro.import_data`  Most likely because we don't have python3?

I will put in a request to install python3 for us

**Comment by jbanfield** [comment]
`python -m crowdastro.import_data
Traceback (most recent call last):
  File "/usr/local/python-2.7.1/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/python-2.7.1/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/priv/myrtle1/julie/crowdastro/crowdastro/import_data.py", line 22, in <module>
    from . import rgz_data as data
  File "crowdastro/rgz_data.py", line 20, in <module>
    import requests
ImportError: No module named requests
`

**Comment by jbanfield** [comment]
I have been told that everything we require should be in `/pkg/linux/anaconda/bin`  However, there is no `python3`  Working on obtaining it.

**Comment by jbanfield** [comment]
Can we use either python3 3.4 or 3.5?

**Comment by chengsoonong** [comment]
@MatthewJA I think it would be better to support both 3.4 and 3.5. I recall that there used to be "@" for matrix multiply which is new python, but I think that's no longer there now. Should be specified in .travis.yml

**Comment by MatthewJA** [comment]
@chengsoonong: If you think we should support 3.4 and 3.5, then I'm happy to support both. At the moment I believe setup.py only specifies 3.5, so I can change that.

@jbanfield: Either 3.4 or 3.5 should be fine.

**Comment by jbanfield** [comment]
I have requested 3.5

**Comment by MatthewJA** [comment]
Just a note, if you have to shut down MongoDB, here's how:

`mongod --dbpath mongodata/ --shutdown`

**Comment by jbanfield** [comment]
The default anaconda python is 2.7. To use python 3.5:source /pkg/linux/anaconda/bin/activate python35

(your prompt will change, showing that you have a new python environment).

To revert to your previous environment:source /pkg/linux/anaconda/bin/deactivate python35

Only works in a bash terminal

**Comment by MatthewJA** [comment]
To get `pip` installing `crowdastro`, you'll need to run it with `--user`.

``` bash
pip install --user crowdastro
```

This should also install all the dependencies.

**Comment by jbanfield** [comment]
Installation is OK.  

Returns error: `ImportError: No module named 'requests_cache'` after running `python -m crowdastro.import_data`

**Comment by MatthewJA** [comment]
I think your version of the code must be out of date, since I removed that dependency. Try:

``` bash
git pull origin master
```

or use the version on `pip` as described above.

**Comment by jbanfield** [comment]
I tried with both and still get the same error.

**Comment by MatthewJA** [comment]
Odd. I'll take a look

**Comment by MatthewJA** [comment]
Yeah, the version on there is out of date. I ran `git pull origin master` and it should work now.

**Comment by MatthewJA** [comment]
Note that this probably erased the changes to `crowdastro.json` you made, since I moved `crowdastro.json`, so you might have to change that again. I need to figure out a way to make configuring this easier...

**Comment by jbanfield** [comment]
there is a crowdastro directory in the crowdastro directory.  Which one do I use?

**Comment by MatthewJA** [comment]
For the JSON configuration? The one inside the _inner_ `crowdastro`. (Again, I'll make this a bit easier at some point).

For actually running it? Be in the outer `crowdastro`. However, it's probably easier to use `pip`. If you `pip install --user crowdastro` you'll get an executable in `~/.local/bin/` called `crowdastro` and you can do things like `crowdastro import_data` instead of `python -m crowdastro.import_data`.

In particular, the [instructions](http://crowdastro.readthedocs.io/en/latest/pipeline/) use the `pip` version, and it's easy to keep it up to date. I would have said this at our last meeting except that the `pip` version didn't exist then &mdash; it's pretty new.

**Comment by jbanfield** [comment]
did you update the fan catalgoue from the email?  I currently only have the version from the email.  If it is the same, I will copy it over.

**Comment by MatthewJA** [comment]
Yes, I pulled out the columns in Excel. I'll copy it over momentarily

**Comment by MatthewJA** [comment]
Copied over. I also copied over `weights.h5` so you don't have to train the CNN.

**Comment by jbanfield** [comment]
OK seems to be working now.  Taking a while to load the data but that is expected.

**Comment by chengsoonong** [comment]
@MatthewJA Worth writing down all these instructions somewhere in the repo.

**Comment by MatthewJA** [comment]
With the exception of the config file (which I'm currently trying to figure out a fix for) this is all in the setup/pipeline instructions on RTD. The specific `pip` instructions are specific to misfit, or at least are very user-dependent.

**Comment by chengsoonong** [comment]
Writing down the RSAA specific instructions on a separate file will be useful to learn what needs to be set up.

**Comment by MatthewJA** [comment]
Ah, okay. I'll do that once Julie has finished running the code, so that I can work through it myself on the RSAA server without interfering with her run. #129

**Comment by MatthewJA** [comment]
Julie has told me that this worked fine.
